services:
  frontend:
    image: sa-frontend
    build: ./frontend
    ports:
      - "3000:3000"
    
  sudoku-service:
    image: sa-sudoku-service
    build:
      context: ./backend/sudoku
      dockerfile: ../Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload
    ports:
      - "8080:8080"